project 'Day01_CustomFont.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
target 'Day01_CustomFont' do
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
    pod 'Alamofire'
end
